class VacuumCleaner{
     public static void main(String XUZ[]){
	 
		System.out.println("PROFESSIONAL UNIQUE DESIGN : It comes in both wired and wireless options. Our handheld vacuum cleaner comes with powerful suction and long lasting power");
		System.out.println("LONG LASTING : It takes just 3 to 4 hours for full charge and uses continuously for up to 25 minutes. You can clean the entire room on a full charge. It is easy to clean hard-to-reach areas like sofa gap, under car seats, corners and others");
		System.out.println("STRONG SUCTION : This cordless vacuum cleaner is equipped with a strong motor and powerful suction capacity which will suck out all kinds of dirt (including hair, fine dust) from the floors to maintain the house clean. It is suitable for dry use only");
		System.out.println("DEEP CLEANING: This small vacuum cleaner cordless can help you to do all-around cleaning with powerful motor and long battery life. The portable vacuum cleaner cleans dust, crumbs, pet hair from carpets, kitchen, living room and offices with outstanding performance");
		System.out.println("INCLUDED COMPONENTS : 1*Long Hose , 1*High Speed C USB Cable, 1*DC Cable,1*Small Nozzle,1*Brush, 1*Carry Bag, 1*Car Vacuum Cleaner ,1*Updated Steel HEPA Filter With1* Pepar HEPA");
	 }
	 }									